### ISSUE TITLE
Use maven to build expath packages

### ISSUE THREAD

**Issue by duncdrum** [schxslt/schxslt#102]
would it make sense to consolidate the make file and pom file, so that `mvn clean package` actually generates the `xar` files?

see https://github.com/claudius108/kuberam-expath-plugin

**Comment by dmj** [comment]
Yes, this would make sense. Thanks for the pointer to the Maven plugin.

**Comment by duncdrum** [comment]
Just one question, would you prefer to stick with the existing single repo making it a modular maven build. Or should both exist and basex become individual repos, which have the jar from this repo as a dependency?

**Comment by duncdrum** [comment]
And one other question, since this doesn't seem to be documented yet, `lib/update-version.xpl` is basically superfluous once the jar and the expath packages are mavenized, or am i missing something here?

**Comment by dmj** [comment]
I seems to me that releasing a new version is easier when there is just one single repository. 

Re update-version.xpl: This pipeline also changes version information in the stylesheets, e.g. src/main/resources/xslt/2.0/version.xsl. I think we can replace this with a parametrized transformation by e.g. http://www.mojohaus.org/xml-maven-plugin/.

**Comment by duncdrum** [comment]
@dmj have  a loot at https://github.com/duncdrum/schxslt/pull/1 

The exist package is still not working as expected and has not tests (but that was the case in v 1.4.2). But if you are happy with the mavenization i ll merge the PR into my branch so i can add tests and modify the xquery module to make sure it is actually working. 

P.S.: i know exist quite well but don't know much about basex, I gather that is more your forte?

**Comment by dmj** [comment]
Thanks, this looks fine! I recently started to work with BaseX on a regular basis, so yes: BaseX is closer to me than eXist. I will look after the BaseX module.
