### ISSUE TITLE
[Question/Feature] Use CI to build and test packages?

### ISSUE THREAD

**Issue by duncdrum** [schxslt/schxslt#104]
With the new maven hotness in #102, should the whole repo use CI for testing commits and deploying packages?

**Comment by dmj** [comment]
I see using CI as a mid-term goal. I would like to understand the build process before starting to abstract away it's details and I'm working on a [conformance testsuite](https://github.com/schxslt/schxslt-testsuite) that I would like to integrate in the build process.

**Comment by duncdrum** [comment]
that would be great, I can help you with the integration. I would however like to automate as much of it as possible early on. Son t nobody got time for manually syncing and compiling all those repos and artifacts.

**Comment by dmj** [comment]
I connected this repository with Travis CI that now runs mvn test on commit.
