### ISSUE TITLE
Exposing XQuery function compile()

### ISSUE THREAD

**Issue by AndrewSales** [schxslt/schxslt#131]
https://github.com/schxslt/schxslt/blob/b39927015784a837fc302bf71cb2aa44cd695d65/basex/src/main/resources/content/schxslt.xqm#L90

by analogy with https://github.com/Schematron/schematron-basex. I can see this being useful in the context of e.g. testing.
(I use @vincentml's implementation in this way, but cannot currently with the SchXslt wrapper without hacking or forking).

**Comment by dmj** [comment]
This sound reasonable.
