### ISSUE TITLE
Does not signal an error if a rule extends an abstract rule defined in a different pattern

### ISSUE THREAD

**Issue by dmj** [schxslt/schxslt#132]
See https://github.com/Schematron/schema/issues/18
See https://github.com/schematron-quickfix/sqf/issues/24
See https://github.com/Schematron/schematron-conformance/commit/455c1efce8274bd31cdbf2f5196383fc5ce00256

**Comment by phax** [comment]
Note: this is a difference in processing from the old schematron/schematron XSLTs
