### ISSUE TITLE
review maven setup

### ISSUE THREAD

**Issue by eduarddrenth** [schxslt/schxslt#145]
This is a bit weird in 1.5:

![image](https://user-images.githubusercontent.com/10200360/94369954-079e5c00-00ed-11eb-8460-ca9f64bfa650.png)

from https://github.com/schxslt/schxslt/blob/master/pom.xml I conclude that schxslt IS meant to be the parent.

When working with maven modules there are some best practices:

- the parent contains no code or resources
- define distribution, developers, repo's, *management, etc. only in the parent pom
- children inherit these from the parent
- parent + modules in one repo
- release to maven only from the parent, release plugin will keep versions updated and in sync
- projects that you want to have their own release schedule should not be in a module

**Comment by eduarddrenth** [comment]
If you decide to adress this issue, you may also want to consider renaming schxslt to schxslt-stylesheets and java to schxslt-java together with the introduction of schxslt-parent.

**Comment by dmj** [comment]
Thanks again! The parent is called schxslt-parent and I published 1.5.1 to adresse the botched Maven setup.
