### ISSUE TITLE
Support Schema-Aware Schematron-Schema.

### ISSUE THREAD

**Issue by beckerjohannes** [schxslt/schxslt#156]
Currently it is not possible to use `schxslt` with Schematron-Schemas that contain schema-aware XPath expressions like:

```xml
<sch:rule context="element(*,kbl:General_wire_occurrence)/Length_information">
...
</sch:rule>
```
With the deprecated (iso schematron)[https://github.com/Schematron/schematron] this was possible. In order to enable this, one had to include the following in the schematron `.sch` file.
```xml
<sch:schema xmlns:sch="http://purl.oclc.org/dsdl/schematron" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" queryBinding="xslt2">
	<xsl:import-schema schema-location="kbl.xsd" namespace="http://www.prostep.org/Car_electric_container/KBL2.3/KBLSchema"/>
	<sch:ns prefix="kbl" uri="http://www.prostep.org/Car_electric_container/KBL2.3/KBLSchema"/>
        ....
</sch:schema>
```
When compiled with `schxslt` the `import-schema` is removed from the result. When compiled with ISO Schematron it is not. 

Result snippet from ISO Schematron:
```xml
 <!--XSD TYPES FOR XSLT2-->
 <xsl:import-schema xmlns:sch="http://purl.oclc.org/dsdl/schematron" schema-location="kbl.xsd" namespace="http://www.prostep.org/Car_electric_container/KBL2.3/KBLSchema"/>
 <!--KEYS AND FUNCTIONS-->
```
This is also explicitly mentioned as "feature" in the ISO Schemtron XSLT [see](https://github.com/Schematron/schematron/blob/77dcd36c53d12ed786c144ece3b2af7694abdc56/trunk/schematron/code/iso_schematron_skeleton_for_saxon.xsl#L139) and [see](https://github.com/Schematron/schematron/blob/77dcd36c53d12ed786c144ece3b2af7694abdc56/trunk/schematron/code/iso_schematron_skeleton_for_saxon.xsl#L661)

**Comment by dmj** [comment]
Good point. Coincidentally I came to the conclusion that the ISO spec is lacking in this regards. The upcoming version 1.6 will allow xsl:import-schema, xsl:include, xsl:import, and xsl:accumulator.

**Comment by beckerjohannes** [comment]
Cool! Thank you!
