### ISSUE TITLE
Make base URI fixup an optional feature

### ISSUE THREAD

**Issue by markdunnoup** [schxslt/schxslt#159]
Our situation is that we have a ruleset that involves nested inclusions:

top-level.sch contains 

```xml
<sch:extends href="include/variables.sch"/>
```

and variables.sch contains

```xml
<sch:let name="lookup" value="document('helpers/lookup.xml')"/>
```

The compiled XSLT contains:

```xml
<xsl:param name="lookup"
  select="document('helpers/lookup.xml') "
  xml:base="file:/C:/SVN/xmlqa/schematron/include/variables.sch"/>
```

Our Schematron was written with “helpers/” as a subfolder of the location of the compiled XSLT, but SchXslt forces it to be relative to the variables.sch module.

This is not how the older Skeleton Schematron compiler works, and @xml:base also means the compiled XSLT is not portable. We currently compile and test Schematron locally in a PC and deploy to a Linux server.

Is the use of @xml:base a deliberate choice? I can’t see anything in the Schematron standard that requires this (but I’ve not read it all). For us it is a barrier to migration to SchXslt.

**Comment by dmj** [comment]
The Schematron standard does indeed not specify how to handle the base URI of an included definition. I chose to perform base URI fixup described in the [XInclude](https://www.w3.org/TR/xinclude/#base) specification. I'll see to make it an optional feature that can be toggled off by a parameter.

**Comment by markdunnoup** [comment]
That's really good to hear, thanks very much!

**Comment by dmj** [comment]
This was a confusion on my part: Base URI fixup is only relevant with regards to sch:include and sch:extends and happens automatically. Assuming that the validation stylesheet has the same base URI as the Schematron is an error. See #179. 

We don't need an option to toggle base URI fixup _at all_.
