### ISSUE TITLE
Should compiled XSLT have @xml:base on root element even when $schxslt.base-uri-fixup is set to false?

### ISSUE THREAD

**Issue by markdunnoup** [schxslt/schxslt#181]
This is an issue when running XSpec for Schematron, since its compiled XSLT is in a temporary folder distinct from the location of the original Schematron file.

See discussion at https://github.com/xspec/xspec/issues/1369

This could be resolved by a patch in XSpec, but it could be regarded as a bug in SchXslt, since it relies on the compiled XSLT being in the same folder as the Schematron file, when relative URIs are involved.

(XSpec currently does not provide a method for compiling with SchXslt with parameter `$schxslt.base-uri-fixup` set to false.)

**Comment by dmj** [comment]
Thanks for bringing this up!

**Comment by dmj** [comment]
No. I think it shouldn't have an xml:base attribute _at all_. See #179

**Comment by dmj** [comment]
I pushed a change that simplifies the whole business: include.xsl does create xml:base attributes. Could you check if this solves this problem?

**Comment by markdunnoup** [comment]
Sorry no, there are a couple of issues.

The recursive inclusion does not work. 

I can fix that by replacing `<xsl:sequence select="$element/*"/>` with `<xsl:apply-templates select="$element/*" mode="schxslt:include"/>` at line 51 of include.xsl 

(The template for `sch:include` may need a similar change but I'm not using that element in my Schematron.)

Also, the compiled stylesheet and the parameters within it are all given `@xml:base="file:/C:/GitHub/schxslt/core/src/main/resources/xslt/2.0/include.xsl"` which means that none of the relative paths in those parameters work and my issue https://github.com/schxslt/schxslt/issues/159 remains unresolved.

**Comment by dmj** [comment]
You are right. I just pushed a complete reimplementation of include.xsl. Could I ask you to check again?

**Comment by markdunnoup** [comment]
I get the same two issues I'm afraid. I think expand.xsl might need some changes as well.

**Comment by dmj** [comment]
All right. Thanks for checking.

**Comment by dmj** [comment]
I think this should be fixed by now. Could I ask you again to check again?

**Comment by markdunnoup** [comment]
This works fine for compiling and running Schematron, but my original problem running XSpec remains.

XSpec compiles the Schematron to a different (temporary) folder from the Schematron file, and so it does not find the lookup files at relative paths.

Adding `@xml:base` just to the root element would fix this. If you think this should be done in a patch to XSpec I will make that comment in the issue there: https://github.com/xspec/xspec/issues/1369

**Comment by dmj** [comment]
> XSpec compiles the Schematron to a different (temporary) folder from the Schematron file, and so it does not find the lookup files at relative paths.

Handling this issue is in general out of scope of SchXslt: I can make sure that base URI fixup happens for relative URI references **in Schematron** (i.e. sch:include/@href, sch:extends/@href) but not in the compiled XSLT. The one who runs the validation stylesheet has to make sure relative URI references in the XPath expressions work.

When I first wrote the extends/include logic I confused "compile time" and "validation time" so to speak.
