### ISSUE TITLE
compilation missing phase when sch:phase fragment is included with sch:include

### ISSUE THREAD

**Issue by dzim** [schxslt/schxslt#184]
schxslt:effective-phase() does seem to be getting called before all sch:includes are resolved.
Therefore I will get an xsl:terminate when I am trying to sch:include the phase fragment that includes the phase I give to the transformation as external parameter.

With the default skeleton implementation bundled with Oxygen this works. 
Shouldn't the implementation be able to handle this use case?

I am using the transformation file pipeline-for-svrl.xsl with schxslt-1.6.2

**Comment by dmj** [comment]
I can confirm this. Thanks for reporting!

**Comment by dmj** [comment]
I tried with the following setup:

```
<sch:schema xmlns:sch="http://purl.oclc.org/dsdl/schematron" queryBinding="xslt2">
  <sch:include href="phase.sch"/>
  <sch:pattern id="pat">
    <sch:rule context="*">
      <sch:assert test="true()"/>
    </sch:rule>
  </sch:pattern>
</sch:schema>
```

```
<sch:phase id="phase" xmlns:sch="http://purl.oclc.org/dsdl/schematron">
  <sch:active pattern="pat"/>
</sch:phase>
```

Running pipeline-for-svrl.xsl with phase=phase works.

**Comment by dzim** [comment]
Indeed, it works perfectly when I am trying to reproduce now. I was mixing up the phases repeatedly. When the phase is non-existent, the transformation fails (as it should).

Sorry for waking you up!
