### ISSUE TITLE
Performance Issue caused by Metadata

### ISSUE THREAD

**Issue by fsteimke** [schxslt/schxslt#192]
Hi,
i have an XSLT Script which processes large XML Files with > 100.000 Records in streaming mode. Every Record is validated against Schematron Rules. For this i compile the Schematron rules into an XSL Script and apply it via _fn:transform_ to every record. 

It works, but is very, very slow when i compile with SchXslt. It's about 3 or 4 times slower compared to compilation with the Skeleton implementation. 

HotSpot Analysis within the Oxygen IDE showed that this is caused by generation of Metadata. When in comment-out the use of variable $metadata in the template that matches /, variable _$report_, in the compiled script, the  transformation gets five times as fast. 

`<!-- <xsl:sequence select="$metadata"/> -->`

Compilation and applying are both done with Saxon-EE in the Oxygen environment.

I do not need any Metadata, since i am only interested in the failed-assert / failed-report elements inside the report.. Commenting out in the Script the results from compilation solves the issue for me, but i think you should know that there is a problem with metadata.

Thanks,
Frank Steimke

**Comment by dmj** [comment]
Thanks for reporting!

**Comment by dmj** [comment]
Upcoming release 1.8 will have a compiler option to turn off the metadata generation.
