### ISSUE TITLE
<value-of> not handled in properties

### ISSUE THREAD

**Issue by xatapult** [schxslt/schxslt#197]
A `<value-of>` element in a `<property>` is not recognized/handled. For instance the following Schematron:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://purl.oclc.org/dsdl/schematron"  queryBinding="xslt3">
  
  <properties>
    <property id="prop1" >PROP1: <value-of select="."/></property>
  </properties>

  <pattern>
    <rule context="/*">
      <assert test="false()" properties="prop1">Whatever</assert>
    </rule>
  </pattern>

</schema>
```

In the SVRL for property `prop1` I see:

```xml
<svrl:property-reference property="prop1">
   <svrl:text>PROP1: </svrl:text>
   <value-of xmlns="http://purl.oclc.org/dsdl/schematron" select="."/>
</svrl:property-reference>
```

From the specification (see for instance appendix N.6) I would expect the `<value-of>` element to work as it does in an assert or report.

BTW: This raises the interesting question what variables are in scope when a property is expanded. I would expect the variables that are *lexically* in scope in the schema, so *not* the variables in the pattern or rule that fired. But I'm not sure about this...

**Comment by dmj** [comment]
Interesting. It is not just the question of variables but also about the context of the query: is it the global document or the node beeing checked? Lexical scope would be hard to achieve: If you have a global XSLT variable and a template-local variable with the same name, the latter shadows the former in such a way that you can't access the global variable.
