### ISSUE TITLE
Fail to locate dmdSec

### ISSUE THREAD

**Issue by M3ssman** [schxslt/schxslt#220]
# Description

## Plattform

* Java11 OpenJDK, Ubuntu 18.04 LTS
* schxslt v1.8.4 as `schxslt-cli.jar`

# Actual Behavior

Using latest CLI-Distribution () to validate METS/'MODS-data with DDB-Schematron for digitized media, schxslt yields 2 strange invalidation results (besides reasonable ones):

```
java -jar schxslt-cli.jar -s ddb_validierung_mets-mods-ap-digitalisierte-medien.sch -d vd16-998423.shareit.xml -v


...
[invalid] /home/hartwig/Projekte/ulb-it-migration/resources/ddb/vd16-998423.shareit.xml failed-assert /Q{http://www.loc.gov/METS/}mets[1] Die mets:dmdSec enthält die bibliographische Beschreibung des Werks. Innerhalb eines METS-Datensatzes muss es mindestens eine mets:dmdSec geben, die MODS-Daten enthält. Ist dies nicht der Fall, wird der Datensatz nicht in die DDB eingespielt. Weitere Informationen zu diesem Element s. METS-Anwendungsprofil Kapitel 2.5
...
[invalid] /home/hartwig/Projekte/ulb-it-migration/resources/ddb/vd16-998423.shareit.xml failed-assert /Q{http://www.loc.gov/METS/}mets[1] Das primäre Strukturelement (primäres mets:div in der mets:structMap[@TYPE='LOGICAL']) muss über das Attribut "ADMID" mit genau einer mets:amdSec verlinkt sein. Ist dies nicht der Fall und der METS-Datensatz verfügt nur über genau eine mets:amdSec wird die Verlinkung bei der Transformation der Daten erzeugt. Weitere Informationen zu diesem Element s. METS-Anwendungsprofil Kapitel 2.1.2.1 und 2.6.1
```

although the METS/MODS contains both sections.

# Expected Behavior

No remarks about invalid dmd && amd sections; similar to Oxygen and DDB-Reports, since
using both files with latest Oxygen (+Schematron Validation) does *not* yield these messages and 
the Validation-Report from DDB also doesn't contain these failures.

## Appendix

Both METS/MODS and used schematron file attached to issue.

[ddb_validierung_data.zip](https://github.com/schxslt/schxslt/files/7473856/ddb_validierung_data.zip)

**Comment by dmj** [comment]
Thanks for reporting. It think this is not a bug: You use XSLT instructions inside the sch:let element, e.g.

```
<sch:let name="work_dmdid">
      <xsl:choose>
         <xsl:when test="//mets:mets/mets:dmdSec[contains(@ID, 'dwork')]">
            <xsl:variable name="root">
               <xsl:copy-of select="/"/>
            </xsl:variable>
            <xsl:for-each select="tokenize(//mets:mets/mets:structMap[@TYPE='LOGICAL']/descendant::mets:div[not(mets:mptr)][1]/@DMDID, ' ')">
               <xsl:variable name="ID" select="."/>
               <xsl:if test="$root//mets:mets/mets:dmdSec[@ID=$ID]/mets:mdWrap/mets:xmlData/mods:mods">
                  <xsl:value-of select="$ID"/>
               </xsl:if>
            </xsl:for-each>
         </xsl:when>
         <xsl:otherwise>
            <xsl:value-of select="//mets:mets/mets:structMap[@TYPE='LOGICAL']/descendant::mets:div[not(mets:mptr)][1]/@DMDID"/>
         </xsl:otherwise>
      </xsl:choose>
   </sch:let>
```
SchXslt follows the specification and uses the element content of the let-element as the value of the variable work_dmdid (see: ISO-Spec, 5.4.6). And the element content of the sch:let are the XSLT instructions. They are not executed during validation but used as the value of the variable.

Possible solution: Define a function that retrieves the dmdSec ID of the work and use it in the variables ```value``` attribute.

```
   <xsl:function name="mets:work_dmdid">
     <xsl:param name="document"/>
     <xsl:choose>
         <xsl:when test="$document//mets:mets/mets:dmdSec[contains(@ID, 'dwork')]">
            <xsl:variable name="root">
               <xsl:copy-of select="$document"/>
            </xsl:variable>
            <xsl:for-each select="tokenize($document//mets:mets/mets:structMap[@TYPE='LOGICAL']/descendant::mets:div[not(mets:mptr)][1]/@DMDID, ' ')">
               <xsl:variable name="ID" select="."/>
               <xsl:if test="$root//mets:mets/mets:dmdSec[@ID=$ID]/mets:mdWrap/mets:xmlData/mods:mods">
                  <xsl:value-of select="$ID"/>
               </xsl:if>
            </xsl:for-each>
         </xsl:when>
         <xsl:otherwise>
            <xsl:value-of select="$document//mets:mets/mets:structMap[@TYPE='LOGICAL']/descendant::mets:div[not(mets:mptr)][1]/@DMDID"/>
         </xsl:otherwise>
     </xsl:choose>
   </xsl:function>
   <sch:let name="work_dmdid" value="mets:work_dmdid(/)"/>
```

**Comment by M3ssman** [comment]
Thanks for your reply!
I tried as you suggested, and alas, the output changed. 
With the functional approach it doesn't print the missing dmdSec-message and the output is way more reasonable.
Since we do not need to handle IDs containing `dwork`, it was possible to shrink the accordingschematron section to:

```
   <xsl:function name="mets:work_dmdid">
     <xsl:param name="document"/>
      <xsl:value-of select="$document//mets:mets/mets:structMap[@TYPE='LOGICAL']/descendant::mets:div[not(mets:mptr)][1]/@DMDID"/>
   </xsl:function>
   <sch:let name="work_dmdid" value="mets:work_dmdid(/)"/>
```

There was still a minor issue on my side, because the DDB schematron labels not only `failed-assert` with invalid roles, but even element `successful-report` with role `error`. Somehow crazy, isn't it? I didn't recognized this at first.

@dmj Would you suggest to report this back to the DDB?

**Comment by dmj** [comment]
Yes, I think this would be a could idea. It's an interoperability problem with the DDB Schematron rules.
