### ISSUE TITLE
Add support for sch:pattern/sch:title as svrl:active-pattern/@name

### ISSUE THREAD

**Issue by BhaaLseN** [schxslt/schxslt#231]
The Schematron skeleton implementation that used to be the prominent one before SchXslt was a thing uses [`sch:pattern/sch:title` to populate the `svrl:active-pattern/@name` attribute](https://github.com/Schematron/schematron/blob/master/trunk/schematron/code/iso_schematron_skeleton_for_saxon.xsl#L1466) (and, as fallback, the `sch:pattern/@id` attribute; but I wonder if that one is of any use.) SchXslt does not use this attribute at all (at least at 1.8.5)

I just patched it into the [`schxslt-api:active-pattern` template](https://github.com/schxslt/schxslt/blob/master/core/src/main/resources/xslt/2.0/svrl.xsl#L50) and it works with the simple Schematron files I got, but I'm not sure if that hits all the cases or missed a spot:
```patch
   <xsl:template name="schxslt-api:active-pattern">
     <xsl:param name="pattern" as="element(sch:pattern)" required="yes"/>
     <xsl:if test="$schxslt.svrl.compact eq false()">
-      <svrl:active-pattern>
+      <svrl:active-pattern name="{($pattern/sch:title, $pattern/@id)[.][1]}">
         <xsl:sequence select="($pattern/@id, $pattern/@role)"/>
         <attribute name="documents" select="base-uri(.)"/>
       </svrl:active-pattern>
     </xsl:if>
   </xsl:template>
```

It would be nice to see this included properly so that reports can show it. Not sure where I got it from, but I have a `svrl2html.xsl` file that generates HTML from the SVRL, and it uses the `svrl:active-pattern/@name` to show some extra context (in addition to the actual assert/report message and their location) in front; which was obviously missing after replacing the schematron XSLTs with SchXslt.

**Comment by dmj** [comment]
Thanks for reporting. This seems to be an easy to thing to fix!

**Comment by dmj** [comment]
I will include this in the upcoming 1.8.6 maintenance release.
