### ISSUE TITLE
unable to resolve-uri() on filepath?

### ISSUE THREAD

**Issue by sydb** [schxslt/schxslt#232]
The [MED01.zip](https://github.com/schxslt/schxslt/files/7777140/MED01.zip) file (**M**ausatron **E**rror **D**emo **01**) contains 2 files: a Schematron schema and an XML instance. When unzipped into your `/tmp/` directory, validating the instance against the schema should result in 3 warning messages from the schema.

Indeed, both oXygen 24.0 and `probatron` do exactly that. But `mausatron` (i.e., `schxslt-cli.jar` from release 1.8.5) fails when it hits line 13, a filepath, complaining that “Base URI {} is not an absolute URI”. Line 17 causes same error. (And presumably lines 14 & 18 do, too.)

**Comment by dmj** [comment]
Thanks for reporting! When ```resolve-uri``` is called with only one argument it resolves the URI given as first argument against the base URI of the static context. Somehow the base uri of the compiled stylesheet gets lost. It should be the base URI of the Schematron schema. This looks like a bug in SchXslt CLI.

**Comment by dmj** [comment]
Side note: The example schema assumes that both, the document instance and the compiled stylesheet exist in the same location. I.e. you resolve the URI in @file against the static base URI of the compiled stylesheet.

**Comment by dmj** [comment]
This one should be fixed in 1.8.6
