### ISSUE TITLE
Why is queryBinding default "xslt", instead of "xslt2" for 2.0 implementation?

### ISSUE THREAD

**Issue by GerbenAbbink** [schxslt/schxslt#288]
I am using the latest "Source Code" stylesheets.

My Schematron is like this (nothing special):

```
<?xml version="1.0" encoding="utf-8"?>
<schema xmlns="http://purl.oclc.org/dsdl/schematron">
	<pattern>
		<rule context="book">
			<assert test="count(chapter)&gt;=3">Book should have 3 chapters or more.</assert>
		</rule>
	</pattern>
</schema>

```
If I run the 1.0 XSLT stylesheet "compile-for-svrl.xsl" against my schematron everything works fine.
However, if I run the 2.0 version against my schematron i get this error message:

The query language 'xslt' is not supported.

If I add queryBinding="xslt2" to the schematron, there is no error.

My question is this: why am I forced to specify the *optional* attribute queryBinding for the 2.0 implementation, because the default value of queryBinding is "xslt", instead of "xslt2"?

**Comment by dmj** [comment]
The default value of the queryBinding attribute defined to be 'xslt'. SchXslt implements the ISO specification very strictly.

**Comment by GerbenAbbink** [comment]
Does this mean that I should use the 1.0 stylesheets if there is no queryBinding attribute, or queryBinding="xslt"?
And use the 2.0 implementation if queryBinding="xslt2" or "xslt3"?

**Comment by dmj** [comment]
Yes, this is the way it should be done. See also #292 that when implemented would give you the option to specify a different default value.

There's also https://github.com/Schematron/schematron-enhancement-proposals/issues/28 that discusses this in the wider context of a potential 4th revision of the specification.

**Comment by GerbenAbbink** [comment]
I didn't know that. Thanks for clearing that up.
