### ISSUE TITLE
Problem with attribute handling in compiler (schxslt:message-template mode)

### ISSUE THREAD

**Issue by markdunnoup** [schxslt/schxslt#289]
In core\src\main\resources\xslt\2.0\compile\templates.xsl there is a template 

```
<xsl:template match="@*" mode="schxslt:variable-content schxslt:message-template">
  <attribute namespace="{namespace-uri(.)}" name="{local-name(.)}">
    <value-of select="."/>
  </attribute>
</xsl:template>
```

In my Schematron rule set I use HTML markup in messages, e.g.

```
<iso:report id="bits-core-rule-103" role="information" flag="information" test=".">
  <p>Sanity Check.</p>
  <table class="dataInfo" style="border:1px dotted black; border-collapse:collapse;" cellpadding="2">
```

In the preprocessed XSL version of the Schematron rule set this becomes:

```
<svrl:successful-report location="{schxslt:location(.)}" role="information" flag="information" id="bits-core-rule-103">
  <xsl:attribute name="test">.</xsl:attribute>
  <svrl:text>
    <xsl:element namespace="" name="p">Sanity Check.</xsl:element>
    <xsl:element namespace="" name="table">
    <xsl:attribute namespace="" name="class">
      <xsl:value-of select="."/>
    </xsl:attribute>
```

The context of this rule is the root node, so the effect of this XSL is to copy the entire text of the source document into the table/@class attribute.

I think the template should read

```
<xsl:template match="@*" mode="schxslt:variable-content schxslt:message-template">
  <attribute namespace="{namespace-uri(.)}" name="{local-name(.)}">
    <xsl:value-of select="."/>
  </attribute>
</xsl:template>
```

In the same compiler file there is another template in the mode schxslt:message-template

```
<xsl:template match="node() | @*" mode="schxslt:message-template">
  <xsl:copy>
    <xsl:apply-templates mode="#current"/>
  </xsl:copy>
</xsl:template>
```

So perhaps an alternative solution is to remove the mode from the first template so that the second template takes precedence.

**Comment by dmj** [comment]
Thanks! This is indeed an error.

**Comment by dmj** [comment]
May I ask which version you are using? This bug was fixed in v1.7.3 of SchXslt Schematron.

**Comment by markdunnoup** [comment]
My apologies, I didn't merge my local copy far enough upstream from my fork. 

I have the latest version now and it is working.

**Comment by dmj** [comment]
No worries!
