### ISSUE TITLE
Do not use document('') function in schxslt-api:metadata template

### ISSUE THREAD

**Issue by kosek** [schxslt/schxslt#293]
For very large Schematron files (and thus generated XSLT files) using document('') function drastically increases memory needed by XSLT processor as XSLT transformation is parsed twice -- once while compiling it and second time as a normal XML input loaded using document() function. As an example for 100 MB XSLT file this could easily consume additional GB of RAM.

**Comment by dmj** [comment]
I track this down to #148 and still trying to figure out why I considered using xsl: a bug.

**Comment by dmj** [comment]
Couldn't figure out why I worked on #148. Will publish a 1.9.4 maintenance release with the use of document('') removed. Thanks for bringing this up!

**Comment by dmj** [comment]
For the records: xsltproc does *not* use the prefix from @result-prefix in the validation stylesheet. We might need to reopen #148 when and if some other processor behaves the same.

**Comment by kosek** [comment]
OK, that's pity. But document('') function can be used conditionally only for XSLT 1.0 processors then.
