### ISSUE TITLE
Some Maven central artifacts are missing

### ISSUE THREAD

**Issue by rpavlik** [schxslt/schxslt#295]
I'm using the cli artifact from Maven Central. I went to upgrade from 1.9.1 and hit 404 errors, and noticed that the latest release that has been published there is 1.9.1, so it's a few behind by now. Can you push the updated versions? (Alternately, can you attach the hashes of the artifacts to the github releases?)

**Comment by dmj** [comment]
Thanks for reporitng! This is an error.

**Comment by dmj** [comment]
I published the artifcat for SchXslt CLI 1.9.4 to Sonatype, they should appear on Maven Central soon. I also added the hashes to the release.

**Comment by rpavlik** [comment]
Thanks!
