### ISSUE TITLE
Cannot build with Java 19

### ISSUE THREAD

**Issue by djbpitt** [schxslt/schxslt#297]
Using MacOS Monterey 12.6 on an Apple Intel box with the following Maven configuration:

```
djb@koala-4 schxslt % mvn --version
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /usr/local/Cellar/maven/3.8.6/libexec
Java version: 19, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk/19/libexec/openjdk.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "12.6", arch: "x86_64", family: "mac"
```
 the build fails with:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for SchXslt Parent 1.10-SNAPSHOT:
[INFO]
[INFO] SchXslt Parent ..................................... SUCCESS [  0.003 s]
[INFO] SchXslt Core ....................................... SUCCESS [ 24.208 s]
[INFO] BaseX Module for Schematron validation with SchXslt  SUCCESS [  1.853 s]
[INFO] eXist Module for Schematron validation with SchXslt  SUCCESS [  0.330 s]
[INFO] SchXslt Ant ........................................ SUCCESS [  3.765 s]
[INFO] SchXslt CLI ........................................ FAILURE [  5.327 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  35.594 s
[INFO] Finished at: 2022-10-29T17:43:58-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:4.2.0:spotbugs (spotbugs) on project cli: Execution spotbugs of goal com.github.spotbugs:spotbugs-maven-plugin:4.2.0:spotbugs failed: Java returned: 1 -> [Help 1]
```

Apparently this has been a known problem with some Java Versions (see <https://stackoverflow.com/questions/62901999/spotbugs-build-issue>), and I was able to build successfully by creating *.mavenrc* with the value:

```
JAVA_HOME=`/usr/libexec/java_home -v 1.8.0`
```

Should this be noted in the SchXslt build documentation?

**Comment by dmj** [comment]
Thanks for reporting! I'll try to reproduce the problem and add a note if I can't find a different solution.

**Comment by utzcoz** [comment]
https://github.com/schxslt/schxslt/pull/298 might be helpful to fix this problem because spotbugs 4.7.3 uses latest ASM 9.4 to support JDK 20 opcode, including supporting JDK 19 opcode.

**Comment by utzcoz** [comment]
Oh, dependabot doesn't find a proper version name for spotbugs-maven-plugin, and I sent a PR(https://github.com/schxslt/schxslt/pull/301) to fix this problem. I tested it locally with JDK 19, and `mvn package` works fine.

**Comment by utzcoz** [comment]
I tested it locally, and spotbugs-maven-plugin 4.7.3.0 fixed schxslt building with JDK 19.

**Comment by dmj** [comment]
I updated the dependency in cli/pom.xml. Thanks for helping to fix this issue!
