### ISSUE TITLE
Not updated on maven central?

### ISSUE THREAD

**Issue by rpavlik** [schxslt/schxslt#314]
I have this integrated into the OpenXR standards pipeline and I'm using the artifacts from Maven Central in my shell script because they have an adjacent hash I can use to verify the download hasn't changed out from underneath us. (I tried to do an SBoM for this but java xml stuff way deep in the dependency tree made it torturous so I just grab it at runtime...) https://github.com/KhronosGroup/OpenXR-Docs/blob/main/specification/registry/schematron.sh

It looks like upload to Maven Central, or maybe the weird sonatype close/publish step (I also publish to maven central), isn't automated at release so 1.9.5 isn't up there yet.

Thanks for your great work on this project! The group is really appreciative of what errors our Schematron rules (checked in CI by schxslt) can help catch in their OpenXR API definitions automatically :)

**Comment by dmj** [comment]
Thanks for the report! Publishing to Maven Central is not automated but requires me manually executing the deploy target. Seems I forgot to publish 1.9.5 on Maven Central because this version only contains a fix in the command line application. I'll push 1.9.5 this afternoon.

**Comment by dmj** [comment]
D'oh! Now I get it. It's the schxslt-cli artifact thats missing :facepalm: Should appear in a couple of hours.
