### ISSUE TITLE
Schematron provided functions missing in XSLT?

### ISSUE THREAD

**Issue by martin-honnen** [schxslt/schxslt#315]
Over on the Saxonica SaxonC user forum https://saxonica.plan.io/issues/6055#note-13 there is a user trying to use Schxslt to perform Schematron validation; however, it seems, that some functions present in the original Schematron schema don't make it into the XSLT Schxslt creates.

Using the current release of schxslt-cli.jar I get errors like

```
java -jar "C:\Users\marti\Downloads\schxslt-cli.jar" -d test.xml -s PEPPOL-EN16931-UBL.sch -v
Static error at /xsl:transform/xsl:template[48]/xsl:choose[1]/xsl:otherwise[1]/schxslt:rule[1]/xsl:if[2] in PEPPOL-EN16931-UBL.sch:
  XPST0017: Cannot find a 1-argument function named Q{utils}TinVerification()
Static error at /xsl:transform/xsl:template[50]/xsl:choose[1]/xsl:otherwise[1]/schxslt:rule[1]/xsl:if[2] in PEPPOL-EN16931-UBL.sch:
  XPST0017: Cannot find a 1-argument function named Q{utils}TinVerification()
Static error at /xsl:transform/xsl:template[51]/xsl:choose[1]/xsl:otherwise[1]/schxslt:rule[1]/xsl:if[1] in PEPPOL-EN16931-UBL.sch:
  XPST0017: Cannot find a 1-argument function named Q{utils}TinVerification()
Static error at /xsl:transform/xsl:template[56]/xsl:choose[1]/xsl:otherwise[1]/schxslt:rule[1]/xsl:if[1] in PEPPOL-EN16931-UBL.sch:
  XPST0017: Cannot find a 1-argument function named Q{utils}TinVerification()
Static error at /xsl:transform/xsl:template[57]/xsl:choose[1]/xsl:otherwise[1]/schxslt:rule[1]/xsl:if[1] in PEPPOL-EN16931-UBL.sch:
  XPST0017: Cannot find a 1-argument function named Q{utils}TinVerification()
Static error at /xsl:transform/xsl:template[58]/xsl:choose[1]/xsl:otherwise[1]/schxslt:rule[1]/xsl:if[1] in PEPPOL-EN16931-UBL.sch:
  XPST0017: Cannot find a 1-argument function named Q{utils}TinVerification()
Exception in thread "main" name.dmaus.schxslt.SchematronException: Unable to create Validator instance
        at name.dmaus.schxslt.Schematron.<init>(Schematron.java:87)
        at name.dmaus.schxslt.Schematron.<init>(Schematron.java:59)
        at name.dmaus.schxslt.Schematron.<init>(Schematron.java:55)
        at name.dmaus.schxslt.cli.Application.main(Application.java:76)
Caused by: javax.xml.transform.TransformerConfigurationException: net.sf.saxon.s9api.SaxonApiException: Errors were reported during stylesheet compilation
        at net.sf.saxon.jaxp.SaxonTransformerFactory.newTemplates(SaxonTransformerFactory.java:152)
        at name.dmaus.schxslt.Schematron.<init>(Schematron.java:84)
        ... 3 more
Caused by: net.sf.saxon.s9api.SaxonApiException: Errors were reported during stylesheet compilation
        at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:793)
        at net.sf.saxon.jaxp.SaxonTransformerFactory.newTemplates(SaxonTransformerFactory.java:149)
        ... 4 more
Caused by: net.sf.saxon.trans.XPathException: Errors were reported during stylesheet compilation
        at net.sf.saxon.style.StylesheetModule.loadStylesheet(StylesheetModule.java:225)
        at net.sf.saxon.style.Compilation.compileSingletonPackage(Compilation.java:107)
        at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:788)
        ... 5 more
```
[PEPPOL-EN16931-UBL.zip](https://github.com/schxslt/schxslt/files/11635270/PEPPOL-EN16931-UBL.zip)

I will attach a zip with the sample XML instance and the Schematron schema; when I try to use oXygen and its built-in Schematron validation support (which I think doesn't use Schxslt) it validates the input fine.

I would like clarification whether this is a bug or quirk in Schxslt or whether there is something wrong with the schema.

**Comment by martin-honnen** [comment]
On further investigation this seems like a problem with the used Schematron schema, the Schematron spec (I have access to) for `xslt2` query binding says `The XSLT2 function element may be used, in the XSLT2 namespace, before the pattern elements.` and it looks as if Schxslt implements that by copying only functions that have no preceding pattern sibling `$schematron/xsl:function[not(preceding-sibling::sch:pattern)]` while the used Schema mixes `pattern` and `function` elements and that way the Schxslt generated lacks the functions declared after the first pattern. So this looks like an error by the author of the Schematron schema and not like a Schxslt issue.

**Comment by dmj** [comment]
> On further investigation this seems like a problem with the used Schematron schema, the Schematron spec (I have access to) for `xslt2` query binding says `The XSLT2 function element may be used, in the XSLT2 namespace, before the pattern elements.` and it looks as if Schxslt implements that by copying only functions that have no preceding pattern sibling `$schematron/xsl:function[not(preceding-sibling::sch:pattern)]` while the used Schema mixes `pattern` and `function` elements and that way the Schxslt generated lacks the functions declared after the first pattern. So this looks like an error by the author of the Schematron schema and not like a Schxslt issue.

Yes, that's correct. SchXslt takes the specification literally in this case.

**Comment by phax** [comment]
@martin-honnen  thanks for highlighting this - I created an OpenPeppol internal ticket (ID PEPPOL-7441) - clearly a bug on our side.

**Comment by Ctrlanton** [comment]
@phax any updates on this? :)
