### ISSUE TITLE
1.10 missing from Maven Central

### ISSUE THREAD

**Issue by rpavlik** [schxslt/schxslt#348]
I have scripts that fetch the CLI jar from maven_central (due to ease and inclusion of hashes) as needed. but https://repo1.maven.org/maven2/name/dmaus/schxslt/cli shows no 1.10 entry.

**Comment by dmj** [comment]
Thanks for the report, I'll check this.

**Comment by dmj** [comment]
Right! I somehow missed publishing it. Should appear in a couple of hours.
