### ISSUE TITLE
Setting the parameter schxslt.compile.metadata to false does not suppress all RDF metadata

### ISSUE THREAD

**Issue by GerbenAbbink** [schxslt/schxslt#349]
Each time SchXSLT runs it creates a different RDF metadata (dct:created). ToroiseSVN, the version control software I use, thinks each time the stylesheet has changed, which is not really true. Is there an option to remove the RDF metadata?

**Comment by dmj** [comment]
Yes, there is: If you set the parameter ```schxslt.compile.metadata``` to ```false``` the output of the metadata is suppressed.

**Comment by GerbenAbbink** [comment]
Perfect! Thank you.

**Comment by GerbenAbbink** [comment]
Actually, there is still a piece that changes everytime I run the transformation, dct:created. Can I also remove dct:created (or  rdf:Description)?

This is what is created by SchXSLT:

```
   <rdf:Description xmlns:dc="http://purl.org/dc/elements/1.1/"
                    xmlns:dct="http://purl.org/dc/terms/"
                    xmlns:skos="http://www.w3.org/2004/02/skos/core#">
      <dct:creator>
         <dct:Agent>
            <skos:prefLabel>SchXslt/1.10 SAXON/HE 12.5</skos:prefLabel>
            <schxslt.compile.typed-variables xmlns="https://doi.org/10.5281/zenodo.1495494#">true</schxslt.compile.typed-variables>
         </dct:Agent>
      </dct:creator>
      <dct:created>2024-10-01T16:10:38.1892685+02:00</dct:created>
   </rdf:Description>

```

**Comment by GerbenAbbink** [comment]
problem is still open.

**Comment by GerbenAbbink** [comment]
Thanks.

**Comment by dmj** [comment]
Okay: Release v1.10.1 with the fix.

**Comment by GerbenAbbink** [comment]
Thanks.
