### ISSUE TITLE
Provide an EXPath package for use in XQuery

### ISSUE THREAD

**Issue by dmj** [schxslt/schxslt#43]
Something like https://github.com/Schematron/schematron-basex

**Comment by vincentml** [comment]
Hi @dmj 

It's good to see this suggestion because I've been thinking about updating [schematron-basex](https://github.com/Schematron/schematron-basex) and [schematron-exist](https://github.com/Schematron/schematron-exist) to switch to the SchXslt implementation of Schematron. 

Perhaps a single EXPath package could be created that contains XQuery modules for BaseX and eXist (and others?). I'm not sure if it would work but it is certainly worth trying.

**Comment by dmj** [comment]
I started one for BaseX but also have the feeling that one for both, BaseX and eXist would be best. Ideally the new package would also be able to compile for XSLT 1.0 with the help of the skeleton.

**Comment by dmj** [comment]
I think the crucial part is the transformation function. BaseX has Q{http://basex.org/modules/xslt}transform and eXist has Q{http://exist-db.org/xquery/transform}transform. I had no luck with [fn:transform](https://www.w3.org/TR/xpath-functions-31/#func-transform) (yet?). One could use [fn:function-lookup](https://www.w3.org/TR/xpath-functions-31/#func-function-lookup) to dynamically select the transformation function.

**Comment by dmj** [comment]
On the other hand: Just start with something simple like two separate modules and think about a single package later. https://github.com/schxslt/schxslt/tree/master/src/main/xquery/basex

**Comment by vincentml** [comment]
> On the other hand: Just start with something simple like two separate modules and think about a single package later. https://github.com/schxslt/schxslt/tree/master/src/main/xquery/basex

That does sound like the easiest approach. This way EXPath packages could be created for BaseX and eXist by the same build script as part of a standard deployment process.

**Comment by dmj** [comment]
I created an eXist module https://github.com/schxslt/schxslt/releases/download/v1.2-rc1/xquery-exist-1.2-rc1.xar but there seems to be a problem with a same-doc-reference at this location: https://github.com/schxslt/schxslt/blob/35336b60a9dd011bd108e2fd4c2ab2285ebf6695/src/main/resources/xslt/compile-for-svrl.xsl#L76 -- If I run schxslt:validate ends up with the error message about not finding the schxslt:location-function.

**Comment by dmj** [comment]
Well, fixed that. Close this issue as per 1.2-rc2
