### ISSUE TITLE
Any improvements over "skeleton" implementation by Rick Jelliffe?

### ISSUE THREAD

**Issue by GerbenAbbink** [schxslt/schxslt#59]
Hi,

We are considering integrating SchXslt in our software. However, we have already integrated the original "skeleton" implementation by Rick Jelliffe.

Can you name a few reasons why our customers would prefer SchXslt over the original implementation? Is it faster? Are the error messages better?

Thank you.

**Comment by dmj** [comment]
Sorry for the delay. The main reason for using SchXslt over the Skeleton would be that SchXslt is actively maintained, well tested and does not suffer from certain defects. It is not faster per se -- in theory the approach taken by SchXslt could make it faster for Schemas that have a lot of patterns, but this is not proven yet.

A reason **not** to use SchXslt is it's "purist" approach: It does not support any of the options you can pass to the Skeleton stylesheet/compiler.

**Comment by GerbenAbbink** [comment]
The original skeleton implementation does not support XSLT 3, how about SchXslt?

**Comment by dmj** [comment]
Right, forgot that. SchXslt supports 'xslt3' as queryBinding and creates an XSLT 3.0 stylesheet.
